-- Actualización de la tabla de auditoría para soportar nuevos módulos
-- Ejecutar en la base de datos de CONTROL

ALTER TABLE `AUDITORIA_LOGS` 
MODIFY COLUMN `TIPO_ACCION` varchar(50) NOT NULL COMMENT 'INSERT|UPDATE|DELETE|LOGIN|LOGOUT|PERMISO_AGREGAR|PERMISO_ELIMINAR|PERMISO_MASIVO|REPORTE_GENERA|REPORTE_BUSCA|REPORTE_DESCARGA|CIERRE_AUTO|CIERRE_MANUAL|BUSQUEDA|FILTRO',
MODIFY COLUMN `ENTIDAD` varchar(50) NOT NULL COMMENT 'USUARIOS|SKILLS|BOT_REDES|PERMISOS|TIPOS_CLIENTE|REPORTES|AUTOMATIZACIONES|TAGS|SEGURIDAD|DESCARGAS_AUTO',
ADD COLUMN `METADATA` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Datos adicionales (filtros de búsqueda, parámetros de reporte, etc.)' CHECK (json_valid(`METADATA`)) AFTER `VALOR_NUEVO`;

-- Asegurarse de que el motor sea InnoDB y charset correcto
-- ALTER TABLE `AUDITORIA_LOGS` ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
