-- Script completo para verificar y actualizar la tabla de auditoría
-- Ejecutar en la base de datos de CONTROL

-- 1. Verificar si la tabla existe
SELECT TABLE_NAME, TABLE_SCHEMA 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_NAME = 'AUDITORIA_LOGS';

-- 2. Si NO existe, crearla completa
CREATE TABLE IF NOT EXISTS `AUDITORIA_LOGS` (
  `ID_LOG` int unsigned NOT NULL AUTO_INCREMENT,
  `FECHA_HORA` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `TIPO_ACCION` varchar(50) NOT NULL COMMENT 'INSERT|UPDATE|DELETE|LOGIN|LOGOUT|PERMISO_AGREGAR|PERMISO_ELIMINAR|PERMISO_MASIVO|REPORTE_GENERA|REPORTE_BUSCA|REPORTE_DESCARGA|CIERRE_AUTO|CIERRE_MANUAL|BUSQUEDA|FILTRO',
  `ENTIDAD` varchar(50) NOT NULL COMMENT 'USUARIOS|SKILLS|BOT_REDES|PERMISOS|TIPOS_CLIENTE|REPORTES|AUTOMATIZACIONES|TAGS|SEGURIDAD|DESCARGAS_AUTO',
  `ID_ENTIDAD` int unsigned DEFAULT NULL,
  `ID_USUARIO_SISTEMA` int unsigned DEFAULT NULL,
  `NOMBRE_USUARIO` varchar(255) DEFAULT NULL,
  `IP_ADDRESS` varchar(45) DEFAULT NULL,
  `USER_AGENT` text,
  `DB_KEY` varchar(20) DEFAULT NULL,
  `DB_NOMBRE` varchar(100) DEFAULT NULL,
  `ID_EMPRESA` int unsigned DEFAULT NULL,
  `NOMBRE_EMPRESA` varchar(255) DEFAULT NULL,
  `ID_USUARIO_AFECTADO` int unsigned DEFAULT NULL,
  `NOMBRE_USUARIO_AFEC` varchar(255) DEFAULT NULL,
  `ID_SKILL` int unsigned DEFAULT NULL,
  `NOMBRE_SKILL` varchar(255) DEFAULT NULL,
  `ID_BOT_RED` int unsigned DEFAULT NULL,
  `NOMBRE_BOT_RED` varchar(255) DEFAULT NULL,
  `ID_TIPO_CLIENTE` int unsigned DEFAULT NULL,
  `NOMBRE_TIPO_CLIENTE` varchar(255) DEFAULT NULL,
  `VALOR_ANTERIOR` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `VALOR_NUEVO` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `METADATA` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`METADATA`)),
  `DESCRIPCION` text,
  `EXITO` tinyint(1) NOT NULL DEFAULT 1,
  `MENSAJE_ERROR` text,
  PRIMARY KEY (`ID_LOG`),
  KEY `idx_fecha_hora` (`FECHA_HORA`),
  KEY `idx_tipo_accion` (`TIPO_ACCION`),
  KEY `idx_entidad` (`ENTIDAD`),
  KEY `idx_db_key` (`DB_KEY`),
  KEY `idx_id_empresa` (`ID_EMPRESA`),
  KEY `idx_usuario` (`ID_USUARIO_SISTEMA`),
  KEY `idx_usuario_afectado` (`ID_USUARIO_AFECTADO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3. Si existe pero no tiene columna METADATA, agregarla
SET @exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'AUDITORIA_LOGS' AND COLUMN_NAME = 'METADATA');

SET @sql = IF(@exists = 0, 
    'ALTER TABLE AUDITORIA_LOGS ADD COLUMN METADATA longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(METADATA)) AFTER VALOR_NUEVO',
    'SELECT "Columna METADATA ya existe" as mensaje');
    
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- 4. Verificar estructura final
DESCRIBE AUDITORIA_LOGS;
