-- Script para crear la tabla PAGINAS_DEMOS en la base de datos de control
-- Similar a NUMEROS_DEMOS pero para páginas de Facebook e Instagram

-- Modificar columna NOMBRE_PAGINA para permitir null (si la tabla ya existe)
ALTER TABLE PAGINAS_DEMOS MODIFY COLUMN NOMBRE_PAGINA VARCHAR(255) NULL;

-- Agregar campo TIPO_DEMO (si no existe)
ALTER TABLE PAGINAS_DEMOS ADD COLUMN TIPO_DEMO ENUM('DEMO_TALKME', 'DEMO_PARTNER', 'CLIENTE') NULL AFTER SEGMENTO;

CREATE TABLE IF NOT EXISTS PAGINAS_DEMOS (
  ID_PAGINA INT AUTO_INCREMENT PRIMARY KEY,
  NOMBRE_PAGINA VARCHAR(255) NULL,
  ID_PAGINA_FB VARCHAR(255) NULL,
  TOKEN TEXT NULL,
  ID_PAGINA_IG VARCHAR(255) NULL,
  NOMBRE_USUARIO_IG VARCHAR(255) NULL,
  RED_SOCIAL ENUM('FACEBOOK', 'INSTAGRAM', 'AMBAS') DEFAULT 'FACEBOOK',
  ESTADO ENUM('DISPONIBLE', 'OCUPADO', 'INACTIVO') DEFAULT 'DISPONIBLE',
  
  -- Campos de mapeo con la base de datos del segmento
  ID_EMPRESA INT NULL,
  ID_BOT INT NULL,
  ID_BOT_REDES INT NULL,
  NOMBRE_EMPRESA VARCHAR(255) NULL,
  SEGMENTO VARCHAR(10) NULL,
  TIPO_DEMO ENUM('DEMO_TALKME', 'DEMO_PARTNER', 'CLIENTE') NULL,
  
  -- Auditoría
  CREADO_POR VARCHAR(100) DEFAULT 'alex.carrera',
  CREADO_EL DATETIME DEFAULT CURRENT_TIMESTAMP,
  ACTUALIZADO_POR VARCHAR(100) NULL,
  ACTUALIZADO_EL DATETIME NULL,
  USADO_EL DATETIME NULL,
  
  INDEX idx_estado (ESTADO),
  INDEX idx_red_social (RED_SOCIAL),
  INDEX idx_segmento (SEGMENTO),
  INDEX idx_nombre_pagina (NOMBRE_PAGINA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
